const bcrypt = require('bcryptjs');
const { v4: uuidv4 } = require('uuid');
const { query } = require('./database');

let initPromise;

async function initDb() {
  // Cache schema initialization per warm serverless instance; retry if it fails.
  if (!initPromise) {
    initPromise = createSchemaAndSeed().catch((err) => {
      initPromise = null;
      throw err;
    });
  }
  return initPromise;
}

async function createSchemaAndSeed() {
  const statements = [
    `CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      uuid TEXT UNIQUE NOT NULL,
      name TEXT NOT NULL,
      email TEXT UNIQUE NOT NULL,
      phone TEXT,
      password TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user','admin')),
      avatar TEXT,
      address TEXT,
      is_active INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS packages (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL UNIQUE,
      category TEXT NOT NULL DEFAULT 'harian' CHECK (category IN ('harian','mingguan','bulanan')),
      catalog_group TEXT NOT NULL DEFAULT 'harian',
      ps_type TEXT NOT NULL CHECK (ps_type IN ('ps4_slim','ps4_pro','ps5')),
      duration INTEGER NOT NULL,
      duration_label TEXT,
      price INTEGER NOT NULL,
      description TEXT,
      features TEXT NOT NULL DEFAULT '[]',
      is_popular INTEGER NOT NULL DEFAULT 0,
      is_active INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS inventory (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      serial_no TEXT UNIQUE NOT NULL,
      ps_type TEXT NOT NULL CHECK (ps_type IN ('ps4_slim','ps4_pro','ps5')),
      name TEXT NOT NULL,
      status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available','rented','maintenance')),
      condition TEXT NOT NULL DEFAULT 'good' CHECK (condition IN ('excellent','good','fair','poor')),
      notes TEXT,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS couriers (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name TEXT NOT NULL,
      phone TEXT NOT NULL,
      email TEXT UNIQUE,
      photo TEXT,
      status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active','off','inactive')),
      total_deliver INTEGER NOT NULL DEFAULT 0,
      rating DOUBLE PRECISION NOT NULL DEFAULT 5.0,
      current_lat DOUBLE PRECISION,
      current_lng DOUBLE PRECISION,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS orders (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_code TEXT UNIQUE NOT NULL,
      user_id INTEGER NOT NULL REFERENCES users(id),
      package_id INTEGER NOT NULL REFERENCES packages(id),
      inventory_id INTEGER REFERENCES inventory(id),
      courier_id INTEGER REFERENCES couriers(id),
      status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','confirmed','preparing','on_delivery','delivered','active','returning','completed','cancelled')),
      payment_method TEXT NOT NULL CHECK (payment_method IN ('bca','gopay','ovo','dana','cod')),
      payment_status TEXT NOT NULL DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid','paid','refunded')),
      subtotal INTEGER NOT NULL,
      delivery_fee INTEGER NOT NULL DEFAULT 15000,
      total INTEGER NOT NULL,
      delivery_address TEXT NOT NULL,
      delivery_lat DOUBLE PRECISION,
      delivery_lng DOUBLE PRECISION,
      start_date TEXT,
      end_date TEXT,
      notes TEXT,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS order_tracking (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id INTEGER NOT NULL REFERENCES orders(id),
      status TEXT NOT NULL,
      message TEXT NOT NULL,
      lat DOUBLE PRECISION,
      lng DOUBLE PRECISION,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS chat_messages (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      room_id TEXT NOT NULL,
      sender_id INTEGER NOT NULL REFERENCES users(id),
      sender_role TEXT NOT NULL CHECK (sender_role IN ('user','admin','courier')),
      message TEXT NOT NULL,
      is_read INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    `CREATE TABLE IF NOT EXISTS reviews (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      order_id INTEGER UNIQUE NOT NULL REFERENCES orders(id),
      user_id INTEGER NOT NULL REFERENCES users(id),
      rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
      comment TEXT,
      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
    )`,
    'CREATE INDEX IF NOT EXISTS idx_orders_user_id ON orders(user_id)',
    'CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status)',
    'CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at)',
    'CREATE INDEX IF NOT EXISTS idx_chat_room_id ON chat_messages(room_id)',
    'CREATE INDEX IF NOT EXISTS idx_tracking_order_id ON order_tracking(order_id)',
    'CREATE INDEX IF NOT EXISTS idx_users_email ON users(email)'
  ];

  for (const statement of statements) await query(statement);

  // Create a first admin only on a brand-new database. No hard-coded password is used.
  const userCount = Number((await query('SELECT COUNT(*)::int AS count FROM users')).rows[0].count);
  if (userCount === 0) {
    const adminPassword = process.env.ADMIN_PASSWORD;
    if (!adminPassword || adminPassword.length < 12) {
      throw new Error('Database users masih kosong. Atur ADMIN_PASSWORD (minimal 12 karakter) di Vercel Environment Variables.');
    }
    const email = (process.env.ADMIN_EMAIL || 'admin@playbox.id').toLowerCase().trim();
    const hash = bcrypt.hashSync(adminPassword, 10);
    await query(
      `INSERT INTO users (uuid, name, email, password, role, address)
       VALUES ($1, $2, $3, $4, 'admin', $5) ON CONFLICT (email) DO NOTHING`,
      [uuidv4(), 'Admin Void Play Box', email, hash, 'Banda Aceh, Aceh']
    );
  }

  await seedPackages();
  await seedInventory();
  await seedCouriers();
  console.log('✅ Skema PostgreSQL siap');
}

async function seedPackages() {
  const count = Number((await query('SELECT COUNT(*)::int AS count FROM packages')).rows[0].count);
  if (count > 0) return;
  const offers = [
    ['Personal 1 Jam', 'personal', 1, '1 Jam', 15000],
    ['Personal 2 Jam', 'personal', 2, '2 Jam', 25000],
    ['Personal 3 Jam', 'personal', 3, '3 Jam', 35000],
    ['Personal 4 Jam', 'personal', 4, '4 Jam', 40000],
    ['Personal 5 Jam', 'personal', 5, '5 Jam', 50000],
    ['Harian Weekday', 'harian', 24, '24 Jam · Weekday', 110000],
    ['Harian Weekend', 'harian', 24, '24 Jam · Weekend', 120000],
    ['Paket Hemat Siang', 'hemat', 4, '13.00–17.00 · 4 Jam', 35000],
    ['Paket Hemat Sore', 'hemat', 6, '17.30–23.30 · 6 Jam', 50000],
    ['Paket Hemat Malam', 'hemat', 9, '00.00–09.00 · 9 Jam', 50000]
  ];
  for (const [name, group, duration, label, price] of offers) {
    const features = JSON.stringify(['PS4 Slim', '2 Controller', 'Pilih jadwal sesuai paket']);
    await query(
      `INSERT INTO packages (name, category, catalog_group, ps_type, duration, duration_label, price, description, features, is_popular)
       VALUES ($1, 'harian', $2, 'ps4_slim', $3, $4, $5, $6, $7, $8)
       ON CONFLICT (name) DO NOTHING`,
      [name, group, duration, label, price, `Sewa PS4 Slim · ${label}`, features, name === 'Harian Weekend' ? 1 : 0]
    );
  }
}

async function seedInventory() {
  const count = Number((await query('SELECT COUNT(*)::int AS count FROM inventory')).rows[0].count);
  if (count > 0) return;
  const items = [
    ['PBX-PS4S-001', 'ps4_slim', 'PS4 Slim - Unit 01', 'available', 'excellent'],
    ['PBX-PS4S-002', 'ps4_slim', 'PS4 Slim - Unit 02', 'available', 'good'],
    ['PBX-PS4S-003', 'ps4_slim', 'PS4 Slim - Unit 03', 'rented', 'good'],
    ['PBX-PS4P-001', 'ps4_pro', 'PS4 Pro - Unit 01', 'available', 'excellent'],
    ['PBX-PS4P-002', 'ps4_pro', 'PS4 Pro - Unit 02', 'rented', 'excellent'],
    ['PBX-PS5-001', 'ps5', 'PS5 - Unit 01', 'available', 'excellent'],
    ['PBX-PS5-002', 'ps5', 'PS5 - Unit 02', 'maintenance', 'fair']
  ];
  for (const item of items) {
    await query(
      `INSERT INTO inventory (serial_no, ps_type, name, status, condition) VALUES ($1,$2,$3,$4,$5)
       ON CONFLICT (serial_no) DO NOTHING`, item
    );
  }
}

async function seedCouriers() {
  const count = Number((await query('SELECT COUNT(*)::int AS count FROM couriers')).rows[0].count);
  if (count > 0) return;
  const items = [
    ['Budi Santoso', '0812-3456-7890', 'budi@playbox.id', 'active', 142, 4.9, 5.5477, 95.3238],
    ['Siti Rahayu', '0856-7890-1234', 'siti@playbox.id', 'active', 98, 4.8, 5.5490, 95.3180],
    ['Andi Kurniawan', '0823-4567-8901', 'andi@playbox.id', 'active', 76, 4.7, 5.5460, 95.3250],
    ['Maya Sari', '0897-6543-2109', 'maya@playbox.id', 'off', 55, 5.0, 5.5500, 95.3200]
  ];
  for (const item of items) {
    await query(
      `INSERT INTO couriers (name, phone, email, status, total_deliver, rating, current_lat, current_lng)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (email) DO NOTHING`, item
    );
  }
}

if (require.main === module) {
  initDb()
    .then(() => process.exit(0))
    .catch((err) => {
      console.error('❌ Gagal inisialisasi PostgreSQL:', err.message);
      process.exit(1);
    });
}

module.exports = { initDb };
